// Belgian data from 2019 extracted from:
// https://population.un.org/wpp/Download/Files/1_Indicators%20(Standard)/CSV_FILES/WPP2019_PopulationBySingleAgeSex_1950-2019.csv

export const populationData = {
    "0-9": 1305219,
    "10-19": 1298970,
    "20-29": 1395385,
    "30-39": 1498535,
    "40-49": 1524152,
    "50-59": 1601891,
    "60-69": 1347696,
    "70-79": 908725,
    "80-89": 535484,
    "90+": 123269,
    "Age unknown": 0,
    "total": 11539326
};
export const rawPopulationData = [
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "0",
        "AgeGrpStart": "0",
        "AgeGrpSpan": "1",
        "PopMale": "62.696",
        "PopFemale": "59.527",
        "PopTotal": "122.223"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "1",
        "AgeGrpStart": "1",
        "AgeGrpSpan": "1",
        "PopMale": "64.426",
        "PopFemale": "60.869",
        "PopTotal": "125.295"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "2",
        "AgeGrpStart": "2",
        "AgeGrpSpan": "1",
        "PopMale": "65.864",
        "PopFemale": "62.009",
        "PopTotal": "127.873"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "3",
        "AgeGrpStart": "3",
        "AgeGrpSpan": "1",
        "PopMale": "67.03",
        "PopFemale": "62.959",
        "PopTotal": "129.989"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "4",
        "AgeGrpStart": "4",
        "AgeGrpSpan": "1",
        "PopMale": "67.374",
        "PopFemale": "63.194",
        "PopTotal": "130.568"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "5",
        "AgeGrpStart": "5",
        "AgeGrpSpan": "1",
        "PopMale": "68.2",
        "PopFemale": "63.993",
        "PopTotal": "132.193"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "6",
        "AgeGrpStart": "6",
        "AgeGrpSpan": "1",
        "PopMale": "68.795",
        "PopFemale": "64.603",
        "PopTotal": "133.398"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "7",
        "AgeGrpStart": "7",
        "AgeGrpSpan": "1",
        "PopMale": "69.174",
        "PopFemale": "65.031",
        "PopTotal": "134.205"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "8",
        "AgeGrpStart": "8",
        "AgeGrpSpan": "1",
        "PopMale": "69.355",
        "PopFemale": "65.286",
        "PopTotal": "134.641"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "9",
        "AgeGrpStart": "9",
        "AgeGrpSpan": "1",
        "PopMale": "69.402",
        "PopFemale": "65.432",
        "PopTotal": "134.834"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "10",
        "AgeGrpStart": "10",
        "AgeGrpSpan": "1",
        "PopMale": "69.38",
        "PopFemale": "65.531",
        "PopTotal": "134.911"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "11",
        "AgeGrpStart": "11",
        "AgeGrpSpan": "1",
        "PopMale": "69.058",
        "PopFemale": "65.321",
        "PopTotal": "134.379"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "12",
        "AgeGrpStart": "12",
        "AgeGrpSpan": "1",
        "PopMale": "68.355",
        "PopFemale": "64.701",
        "PopTotal": "133.056"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "13",
        "AgeGrpStart": "13",
        "AgeGrpSpan": "1",
        "PopMale": "67.434",
        "PopFemale": "63.844",
        "PopTotal": "131.278"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "14",
        "AgeGrpStart": "14",
        "AgeGrpSpan": "1",
        "PopMale": "66.544",
        "PopFemale": "63.031",
        "PopTotal": "129.575"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "15",
        "AgeGrpStart": "15",
        "AgeGrpSpan": "1",
        "PopMale": "65.64",
        "PopFemale": "62.216",
        "PopTotal": "127.856"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "16",
        "AgeGrpStart": "16",
        "AgeGrpSpan": "1",
        "PopMale": "65.048",
        "PopFemale": "61.675",
        "PopTotal": "126.723"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "17",
        "AgeGrpStart": "17",
        "AgeGrpSpan": "1",
        "PopMale": "64.957",
        "PopFemale": "61.576",
        "PopTotal": "126.533"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "18",
        "AgeGrpStart": "18",
        "AgeGrpSpan": "1",
        "PopMale": "65.246",
        "PopFemale": "61.824",
        "PopTotal": "127.07"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "19",
        "AgeGrpStart": "19",
        "AgeGrpSpan": "1",
        "PopMale": "65.516",
        "PopFemale": "62.073",
        "PopTotal": "127.589"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "20",
        "AgeGrpStart": "20",
        "AgeGrpSpan": "1",
        "PopMale": "65.739",
        "PopFemale": "62.299",
        "PopTotal": "128.038"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "21",
        "AgeGrpStart": "21",
        "AgeGrpSpan": "1",
        "PopMale": "66.442",
        "PopFemale": "63.008",
        "PopTotal": "129.45"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "22",
        "AgeGrpStart": "22",
        "AgeGrpSpan": "1",
        "PopMale": "67.815",
        "PopFemale": "64.386",
        "PopTotal": "132.201"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "23",
        "AgeGrpStart": "23",
        "AgeGrpSpan": "1",
        "PopMale": "69.583",
        "PopFemale": "66.178",
        "PopTotal": "135.761"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "24",
        "AgeGrpStart": "24",
        "AgeGrpSpan": "1",
        "PopMale": "71.333",
        "PopFemale": "67.964",
        "PopTotal": "139.297"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "25",
        "AgeGrpStart": "25",
        "AgeGrpSpan": "1",
        "PopMale": "73.207",
        "PopFemale": "69.856",
        "PopTotal": "143.063"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "26",
        "AgeGrpStart": "26",
        "AgeGrpSpan": "1",
        "PopMale": "74.512",
        "PopFemale": "71.355",
        "PopTotal": "145.867"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "27",
        "AgeGrpStart": "27",
        "AgeGrpSpan": "1",
        "PopMale": "74.881",
        "PopFemale": "72.178",
        "PopTotal": "147.059"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "28",
        "AgeGrpStart": "28",
        "AgeGrpSpan": "1",
        "PopMale": "74.642",
        "PopFemale": "72.551",
        "PopTotal": "147.193"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "29",
        "AgeGrpStart": "29",
        "AgeGrpSpan": "1",
        "PopMale": "74.488",
        "PopFemale": "72.968",
        "PopTotal": "147.456"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "30",
        "AgeGrpStart": "30",
        "AgeGrpSpan": "1",
        "PopMale": "74.277",
        "PopFemale": "73.308",
        "PopTotal": "147.585"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "31",
        "AgeGrpStart": "31",
        "AgeGrpSpan": "1",
        "PopMale": "74.183",
        "PopFemale": "73.699",
        "PopTotal": "147.882"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "32",
        "AgeGrpStart": "32",
        "AgeGrpSpan": "1",
        "PopMale": "74.363",
        "PopFemale": "74.247",
        "PopTotal": "148.61"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "33",
        "AgeGrpStart": "33",
        "AgeGrpSpan": "1",
        "PopMale": "74.706",
        "PopFemale": "74.853",
        "PopTotal": "149.559"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "34",
        "AgeGrpStart": "34",
        "AgeGrpSpan": "1",
        "PopMale": "74.964",
        "PopFemale": "75.357",
        "PopTotal": "150.321"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "35",
        "AgeGrpStart": "35",
        "AgeGrpSpan": "1",
        "PopMale": "75.204",
        "PopFemale": "75.851",
        "PopTotal": "151.055"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "36",
        "AgeGrpStart": "36",
        "AgeGrpSpan": "1",
        "PopMale": "75.391",
        "PopFemale": "76.023",
        "PopTotal": "151.414"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "37",
        "AgeGrpStart": "37",
        "AgeGrpSpan": "1",
        "PopMale": "75.492",
        "PopFemale": "75.72",
        "PopTotal": "151.212"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "38",
        "AgeGrpStart": "38",
        "AgeGrpSpan": "1",
        "PopMale": "75.553",
        "PopFemale": "75.126",
        "PopTotal": "150.679"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "39",
        "AgeGrpStart": "39",
        "AgeGrpSpan": "1",
        "PopMale": "75.645",
        "PopFemale": "74.573",
        "PopTotal": "150.218"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "40",
        "AgeGrpStart": "40",
        "AgeGrpSpan": "1",
        "PopMale": "75.743",
        "PopFemale": "73.991",
        "PopTotal": "149.734"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "41",
        "AgeGrpStart": "41",
        "AgeGrpSpan": "1",
        "PopMale": "75.961",
        "PopFemale": "73.622",
        "PopTotal": "149.583"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "42",
        "AgeGrpStart": "42",
        "AgeGrpSpan": "1",
        "PopMale": "76.358",
        "PopFemale": "73.617",
        "PopTotal": "149.975"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "43",
        "AgeGrpStart": "43",
        "AgeGrpSpan": "1",
        "PopMale": "76.88",
        "PopFemale": "73.869",
        "PopTotal": "150.749"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "44",
        "AgeGrpStart": "44",
        "AgeGrpSpan": "1",
        "PopMale": "77.387",
        "PopFemale": "74.089",
        "PopTotal": "151.476"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "45",
        "AgeGrpStart": "45",
        "AgeGrpSpan": "1",
        "PopMale": "77.882",
        "PopFemale": "74.294",
        "PopTotal": "152.176"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "46",
        "AgeGrpStart": "46",
        "AgeGrpSpan": "1",
        "PopMale": "78.434",
        "PopFemale": "74.686",
        "PopTotal": "153.12"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "47",
        "AgeGrpStart": "47",
        "AgeGrpSpan": "1",
        "PopMale": "79.056",
        "PopFemale": "75.325",
        "PopTotal": "154.381"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "48",
        "AgeGrpStart": "48",
        "AgeGrpSpan": "1",
        "PopMale": "79.704",
        "PopFemale": "76.115",
        "PopTotal": "155.819"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "49",
        "AgeGrpStart": "49",
        "AgeGrpSpan": "1",
        "PopMale": "80.273",
        "PopFemale": "76.866",
        "PopTotal": "157.139"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "50",
        "AgeGrpStart": "50",
        "AgeGrpSpan": "1",
        "PopMale": "80.726",
        "PopFemale": "77.57",
        "PopTotal": "158.296"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "51",
        "AgeGrpStart": "51",
        "AgeGrpSpan": "1",
        "PopMale": "81.195",
        "PopFemale": "78.248",
        "PopTotal": "159.443"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "52",
        "AgeGrpStart": "52",
        "AgeGrpSpan": "1",
        "PopMale": "81.717",
        "PopFemale": "78.878",
        "PopTotal": "160.595"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "53",
        "AgeGrpStart": "53",
        "AgeGrpSpan": "1",
        "PopMale": "82.185",
        "PopFemale": "79.412",
        "PopTotal": "161.597"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "54",
        "AgeGrpStart": "54",
        "AgeGrpSpan": "1",
        "PopMale": "82.495",
        "PopFemale": "79.85",
        "PopTotal": "162.345"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "55",
        "AgeGrpStart": "55",
        "AgeGrpSpan": "1",
        "PopMale": "82.715",
        "PopFemale": "80.223",
        "PopTotal": "162.938"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "56",
        "AgeGrpStart": "56",
        "AgeGrpSpan": "1",
        "PopMale": "82.38",
        "PopFemale": "80.18",
        "PopTotal": "162.56"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "57",
        "AgeGrpStart": "57",
        "AgeGrpSpan": "1",
        "PopMale": "81.264",
        "PopFemale": "79.555",
        "PopTotal": "160.819"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "58",
        "AgeGrpStart": "58",
        "AgeGrpSpan": "1",
        "PopMale": "79.583",
        "PopFemale": "78.502",
        "PopTotal": "158.085"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "59",
        "AgeGrpStart": "59",
        "AgeGrpSpan": "1",
        "PopMale": "77.829",
        "PopFemale": "77.384",
        "PopTotal": "155.213"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "60",
        "AgeGrpStart": "60",
        "AgeGrpSpan": "1",
        "PopMale": "75.963",
        "PopFemale": "76.183",
        "PopTotal": "152.146"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "61",
        "AgeGrpStart": "61",
        "AgeGrpSpan": "1",
        "PopMale": "73.886",
        "PopFemale": "74.758",
        "PopTotal": "148.644"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "62",
        "AgeGrpStart": "62",
        "AgeGrpSpan": "1",
        "PopMale": "71.618",
        "PopFemale": "73.095",
        "PopTotal": "144.713"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "63",
        "AgeGrpStart": "63",
        "AgeGrpSpan": "1",
        "PopMale": "69.229",
        "PopFemale": "71.279",
        "PopTotal": "140.508"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "64",
        "AgeGrpStart": "64",
        "AgeGrpSpan": "1",
        "PopMale": "66.675",
        "PopFemale": "69.313",
        "PopTotal": "135.988"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "65",
        "AgeGrpStart": "65",
        "AgeGrpSpan": "1",
        "PopMale": "63.858",
        "PopFemale": "67.076",
        "PopTotal": "130.934"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "66",
        "AgeGrpStart": "66",
        "AgeGrpSpan": "1",
        "PopMale": "61.508",
        "PopFemale": "65.325",
        "PopTotal": "126.833"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "67",
        "AgeGrpStart": "67",
        "AgeGrpSpan": "1",
        "PopMale": "59.949",
        "PopFemale": "64.399",
        "PopTotal": "124.348"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "68",
        "AgeGrpStart": "68",
        "AgeGrpSpan": "1",
        "PopMale": "58.816",
        "PopFemale": "63.905",
        "PopTotal": "122.721"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "69",
        "AgeGrpStart": "69",
        "AgeGrpSpan": "1",
        "PopMale": "57.57",
        "PopFemale": "63.291",
        "PopTotal": "120.861"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "70",
        "AgeGrpStart": "70",
        "AgeGrpSpan": "1",
        "PopMale": "56.501",
        "PopFemale": "62.883",
        "PopTotal": "119.384"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "71",
        "AgeGrpStart": "71",
        "AgeGrpSpan": "1",
        "PopMale": "54.452",
        "PopFemale": "61.322",
        "PopTotal": "115.774"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "72",
        "AgeGrpStart": "72",
        "AgeGrpSpan": "1",
        "PopMale": "50.849",
        "PopFemale": "57.941",
        "PopTotal": "108.79"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "73",
        "AgeGrpStart": "73",
        "AgeGrpSpan": "1",
        "PopMale": "46.328",
        "PopFemale": "53.487",
        "PopTotal": "99.815"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "74",
        "AgeGrpStart": "74",
        "AgeGrpSpan": "1",
        "PopMale": "41.989",
        "PopFemale": "49.227",
        "PopTotal": "91.216"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "75",
        "AgeGrpStart": "75",
        "AgeGrpSpan": "1",
        "PopMale": "37.482",
        "PopFemale": "44.742",
        "PopTotal": "82.224"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "76",
        "AgeGrpStart": "76",
        "AgeGrpSpan": "1",
        "PopMale": "34.013",
        "PopFemale": "41.526",
        "PopTotal": "75.539"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "77",
        "AgeGrpStart": "77",
        "AgeGrpSpan": "1",
        "PopMale": "32.25",
        "PopFemale": "40.398",
        "PopTotal": "72.648"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "78",
        "AgeGrpStart": "78",
        "AgeGrpSpan": "1",
        "PopMale": "31.57",
        "PopFemale": "40.581",
        "PopTotal": "72.151"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "79",
        "AgeGrpStart": "79",
        "AgeGrpSpan": "1",
        "PopMale": "30.702",
        "PopFemale": "40.482",
        "PopTotal": "71.184"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "80",
        "AgeGrpStart": "80",
        "AgeGrpSpan": "1",
        "PopMale": "29.93",
        "PopFemale": "40.418",
        "PopTotal": "70.348"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "81",
        "AgeGrpStart": "81",
        "AgeGrpSpan": "1",
        "PopMale": "28.749",
        "PopFemale": "39.879",
        "PopTotal": "68.628"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "82",
        "AgeGrpStart": "82",
        "AgeGrpSpan": "1",
        "PopMale": "26.791",
        "PopFemale": "38.449",
        "PopTotal": "65.24"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "83",
        "AgeGrpStart": "83",
        "AgeGrpSpan": "1",
        "PopMale": "24.342",
        "PopFemale": "36.404",
        "PopTotal": "60.746"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "84",
        "AgeGrpStart": "84",
        "AgeGrpSpan": "1",
        "PopMale": "22.098",
        "PopFemale": "34.506",
        "PopTotal": "56.604"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "85",
        "AgeGrpStart": "85",
        "AgeGrpSpan": "1",
        "PopMale": "19.966",
        "PopFemale": "32.682",
        "PopTotal": "52.648"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "86",
        "AgeGrpStart": "86",
        "AgeGrpSpan": "1",
        "PopMale": "17.764",
        "PopFemale": "30.46",
        "PopTotal": "48.224"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "87",
        "AgeGrpStart": "87",
        "AgeGrpSpan": "1",
        "PopMale": "15.485",
        "PopFemale": "27.709",
        "PopTotal": "43.194"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "88",
        "AgeGrpStart": "88",
        "AgeGrpSpan": "1",
        "PopMale": "13.199",
        "PopFemale": "24.627",
        "PopTotal": "37.826"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "89",
        "AgeGrpStart": "89",
        "AgeGrpSpan": "1",
        "PopMale": "10.73",
        "PopFemale": "21.296",
        "PopTotal": "32.026"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "90",
        "AgeGrpStart": "90",
        "AgeGrpSpan": "1",
        "PopMale": "8.652",
        "PopFemale": "18.517",
        "PopTotal": "27.169"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "91",
        "AgeGrpStart": "91",
        "AgeGrpSpan": "1",
        "PopMale": "7.281",
        "PopFemale": "16.283",
        "PopTotal": "23.564"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "92",
        "AgeGrpStart": "92",
        "AgeGrpSpan": "1",
        "PopMale": "5.754",
        "PopFemale": "13.483",
        "PopTotal": "19.237"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "93",
        "AgeGrpStart": "93",
        "AgeGrpSpan": "1",
        "PopMale": "4.06",
        "PopFemale": "10.126",
        "PopTotal": "14.186"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "94",
        "AgeGrpStart": "94",
        "AgeGrpSpan": "1",
        "PopMale": "2.886",
        "PopFemale": "7.789",
        "PopTotal": "10.675"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "95",
        "AgeGrpStart": "95",
        "AgeGrpSpan": "1",
        "PopMale": "2.377",
        "PopFemale": "6.79",
        "PopTotal": "9.167"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "96",
        "AgeGrpStart": "96",
        "AgeGrpSpan": "1",
        "PopMale": "1.921",
        "PopFemale": "5.648",
        "PopTotal": "7.569"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "97",
        "AgeGrpStart": "97",
        "AgeGrpSpan": "1",
        "PopMale": "1.349",
        "PopFemale": "4.13",
        "PopTotal": "5.479"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "98",
        "AgeGrpStart": "98",
        "AgeGrpSpan": "1",
        "PopMale": "0.663",
        "PopFemale": "2.234",
        "PopTotal": "2.897"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "99",
        "AgeGrpStart": "99",
        "AgeGrpSpan": "1",
        "PopMale": "0.317",
        "PopFemale": "1.236",
        "PopTotal": "1.553"
    },
    {
        "LocID": "56",
        "Location": "Belgium",
        "VarID": "2",
        "Variant": "Medium",
        "Time": "2019",
        "MidPeriod": "2019.5",
        "AgeGrp": "100",
        "AgeGrpStart": "100",
        "AgeGrpSpan": "-1",
        "PopMale": "0.276",
        "PopFemale": "1.497",
        "PopTotal": "1.773"
    }
];
